### ISSUE TITLE
Setting subtitles

### ISSUE THREAD

**Issue by siuying** [RSATom/WebChimera.js#34] opened 2015-08-02 14:03 UTC
Refering the javascript API at http://wiki.webchimera.org/Player_JavaScript_API

I'm trying to set the subtitles to a downloaded file on wcjs-player in an electron app:
```
var subtitles = {}
subtitles[language] = subtitlePath
```
where subtitlePath is a local temp file path (``/var/tmp/somesubs.srt``)

I found the player (wcjs-player) seems to know that I pass the subtitles (there is an option for me to choose that subtitles), but when I actually select it, no subtitle is shown.

**Comment by RSATom** [comment] 2015-08-02 14:16
You looked at docs for `WebChimera Player`, but you need docs for `WebChimera.js Player`: https://github.com/jaruba/wcjs-player/wiki/JavaScript-API

**Comment by siuying** [comment] 2015-08-02 14:18
Thanks, but it seems the parameters is the same: 

https://github.com/jaruba/wcjs-player/wiki/addPlaylist-Parameters
``
player.addPlaylist({
    url: "http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4",
    subtitles: {
        "Hungarian": "http://my.subtitle.server/hungarian.srt",
        "Polish": "http://my.subtitle.server/polish.sub"
    }
});
``

I just wonder can I pass a local file instead of HTTP url?

**Comment by RSATom** [comment] 2015-08-02 14:20
let's summon @Jaruba, he should know better.

**Comment by jaruba** [comment] 2015-08-02 14:29
@siuying Loading local subtitle files creates the issue of encoding detection, because subtitle files are never encoded correctly and NW.js / Electron only support UTF-8.

**Comment by siuying** [comment] 2015-08-02 14:41
@jaruba do you mean that its currently not working no matter what file I used? I think the subs I'm testing is just ASCII or UTF8 which should be fine. I'm thinking if I pass wrong parameter (I tried file:// url and path)

**Comment by jaruba** [comment] 2015-08-02 14:47
try ``file:///`` + path

**Comment by jaruba** [comment] 2015-08-02 14:57
if it doesn't work, do a ``console.log()`` with the path and paste it here so I can check it too

**Comment by siuying** [comment] 2015-08-02 15:04
Thats strange, using file:// or file:// will not work, I've even tried to use http:// ...

![](https://s3.amazonaws.com/f.cl.ly/items/10151E3C3a16302H0m1r/Screen%20Shot%202015-08-02%20at%2011.01.34%20pm.png)

![](https://s3.amazonaws.com/f.cl.ly/items/2Y3N213C2I1T15360M2H/Screen%20Shot%202015-08-02%20at%2010.58.18%20pm.png)

**Comment by jaruba** [comment] 2015-08-02 15:09
for dropbox link, it ends in ``.srt?dl=1``, so the player can't identify the subtitle file format to decode it.

**Comment by jaruba** [comment] 2015-08-02 15:13
Also, i'm not sure if SSL is currently supported as I'm using ``require("http").get()`` to fetch the subtitles

The entire subtitle implementation is here:

https://github.com/jaruba/wcjs-player/blob/master/index.js#L1703-L1769

Your welcome to try to improve it if you think you can.

About the local file, try loading that exact link into the browser and see if it starts downloading that local file.

**Comment by siuying** [comment] 2015-08-02 15:17
this is a good lead, I'll look into it, thanks!

**Comment by siuying** [comment] 2015-08-02 17:44
Thanks @jaruba! I'm more clear with the problem now.

1. For some reason at https://github.com/jaruba/wcjs-player/blob/master/index.js#L1681 , newSub will never become 0 when I select subtitles, so loadSubtitle will not get called.
2. If i bypass the check (set newSub = 1), the loadSubtitle would download the subtitles using http. Thats why currently subtitle via ``file://`` will not work. 

For 2. I think I could add local file support. By I'm not sure about 1.

**Comment by jaruba** [comment] 2015-08-02 18:30
how are you selecting your subtitle? with ``.subTrack()`` or through the menu?

**Comment by jaruba** [comment] 2015-08-02 19:05
I can reproduce your issue by selecting the subtitle through the menu, it happens only when the video has no internal subtitles. Ill try to fix it, add https support and see what I can do for the ``file:///`` protocol.

**Comment by jaruba** [comment] 2015-08-02 20:22
I've released a new version of ``WebChimera.js Player``. It now uses the ``request`` module to handle the ``http`` and ``https`` protocols and the ``fs`` module to handle direct and relative paths to local files. (you don't need to use the ``file:///`` protocol, although I still think this will be problematic because of encoding issues)

Also fixed subtitle selection (when there are no internal subtitles available) and I check for ``$_GET`` parameters in the subtitle extension. (and obviously remove them if found)

Please test it when you have time.

**Comment by siuying** [comment] 2015-08-03 02:03
Work like a charm!

![](https://s3.amazonaws.com/f.cl.ly/items/2x4106222T3d2m410Y3n/succeed.jpg)

**Comment by jaruba** [comment] 2015-08-03 02:14
great! :))

**Comment by jaruba** [comment] 2015-08-03 02:57
don't forget to close the issue. :)

**Comment by siuying** [comment] 2015-08-03 04:20
@jaruba Thanks!!

**Closed** 2015-08-03 04:20 UTC
