### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by creativefull** [RSATom/WebChimera.js#60] opened 2015-12-19 05:22 UTC
HI i got error like this .
```
Error: The specified module could not be found.
C:\Users\Windows7\AppData\Local\Temp\nw2940_12978\node_modules\webchimera.js\Release\WebChimera.js.node
```
before i compile my application alright .

**Comment by jaruba** [comment] 2015-12-19 05:30
`WebChimera.js` also needs you to add the VLC binaries to the same folder as `WebChimera.js.node`

What platform are you on?

**Comment by jaruba** [comment] 2015-12-19 05:30
If your looking for an automatic solution to this, you might want to look into:
https://github.com/Ivshti/wcjs-prebuilt

**Comment by creativefull** [comment] 2015-12-19 05:32
i using windows 7 ..

![capture](https://cloud.githubusercontent.com/assets/13174684/11911576/8b87b5a8-a64c-11e5-886d-3d3750720541.PNG)

**Comment by creativefull** [comment] 2015-12-19 05:33
yes i have used wcjs-prebuilt ,. it's working in developer mode ,.
but after i compile my app ,. i get that error

**Comment by RSATom** [comment] 2015-12-19 05:34
you could use http://www.dependencywalker.com/ to find out what exactly it missing

**Comment by RSATom** [comment] 2015-12-19 05:34
I think you just use ia32 .node + x64 VLC or vice versa

**Comment by jaruba** [comment] 2015-12-19 05:36
@RSATom that usually gives the architecture error..

I think this is more related to:
https://github.com/jaruba/wcjs-player/issues/21
and
https://github.com/RSATom/WebChimera.js/issues/29

@creativefull how are you packaging your app?

**Comment by creativefull** [comment] 2015-12-19 05:36
i'm using x64.node + x64 VLC ,.

i get thats error after distribute my app

**Comment by creativefull** [comment] 2015-12-19 05:39
i install webchimera.Js using Prebuilt on windows following this tutorial

https://github.com/RSATom/WebChimera.js#using-prebuilt-on-windows

**Comment by RSATom** [comment] 2015-12-19 05:48
then run `Dependency Walker` over installed `WebChimera.js.node`

**Comment by creativefull** [comment] 2015-12-19 06:01
yes i got error like this ,..
![capture](https://cloud.githubusercontent.com/assets/13174684/11911683/7dc49126-a650-11e5-858a-8da45a3519b2.PNG)

then how to fix it ?

**Comment by creativefull** [comment] 2015-12-19 06:03
i got error like this .
![capture2](https://cloud.githubusercontent.com/assets/13174684/11911691/eb3cd09c-a650-11e5-8c66-09f3974b67f1.PNG)

how to fix it ?

**Comment by RSATom** [comment] 2015-12-19 06:06
It's ok, since you don't have `Electron` in your PATH (but you don't require it to run it successfully).

Are you sure use Electron x64 build?

**Comment by RSATom** [comment] 2015-12-19 06:07
ha... it seems you use `NW.js` not `Electron`, right?

**Comment by creativefull** [comment] 2015-12-19 06:08
yes i'm using NW.js ,

**Comment by RSATom** [comment] 2015-12-19 06:09
Then you just downloaded wrong 'WebChimera.js.node'. Your current is for `Electron`

**Comment by RSATom** [comment] 2015-12-19 06:10
stop

**Comment by RSATom** [comment] 2015-12-19 06:10
I'm wrong

**Comment by creativefull** [comment] 2015-12-19 06:14
Before i compiled application i did'nt get error
![developer](https://cloud.githubusercontent.com/assets/13174684/11911734/5cc3f834-a652-11e5-87b8-7ec12cd10860.PNG)

**Comment by RSATom** [comment] 2015-12-19 06:15
Do you have installer I could test?

**Comment by creativefull** [comment] 2015-12-19 06:16
![production](https://cloud.githubusercontent.com/assets/13174684/11911744/a9771a26-a652-11e5-9a5f-8443c1e3c8fa.PNG)
after compiled like this

**Comment by creativefull** [comment] 2015-12-19 06:17
i have ,..
how to send for you ?

**Comment by RSATom** [comment] 2015-12-19 06:18
you could put it to dropbox (or something similar) and email link to `rsatom on gmail.com`

**Comment by creativefull** [comment] 2015-12-19 06:20
okeh wait ,..

**Comment by creativefull** [comment] 2015-12-19 06:25
My application is still a lot of problems , .
maybe I'll fix it first
:)

**Comment by creativefull** [comment] 2015-12-19 06:25
one error like the one in the picture earlier

**Comment by luigiplr** [comment] 2015-12-19 06:32
@creativefull Mind passing me a link to the repo? Ill take a look.

**Comment by RSATom** [comment] 2015-12-19 06:35
@creativefull, don't worry, I will not even try run it, so it's ok.

**Comment by creativefull** [comment] 2015-12-19 06:36
@luigiplr sorry bro this is private app for my product :)

**Comment by creativefull** [comment] 2015-12-19 06:36
@RSATom OK ,. i'll give you in compiled app

**Comment by luigiplr** [comment] 2015-12-19 06:39
@creativefull okay in that case i suggest you take a look how Powder player does it. (grunt file)

https://github.com/jaruba/PowderPlayer/blob/react-powder/Gruntfile.js#L223

https://github.com/jaruba/PowderPlayer/blob/react-powder/Gruntfile.js#L231

https://github.com/jaruba/PowderPlayer/blob/react-powder/Gruntfile.js#L106

https://github.com/jaruba/PowderPlayer/blob/react-powder/src/components/Player/components/Renderer.react.js#L47

https://github.com/jaruba/PowderPlayer/blob/react-powder/src/components/Player/utils/wcjs-renderer.js#L149

**Comment by creativefull** [comment] 2015-12-19 06:40
@luigiplr ok I know , . but there is no time for that , .. i've deadline for this app

**Comment by creativefull** [comment] 2015-12-19 06:46
@RSATom sorry my internet very slow , i can't upload in my dropbox :( 
![dropbox](https://cloud.githubusercontent.com/assets/13174684/11911865/f0f4775a-a656-11e5-8b51-7b15bf55d636.PNG)

**Comment by luigiplr** [comment] 2015-12-19 06:47
@creativefull 89 MB? Whoa.

Anyway perhaps try Mega or Google Drive.

**Comment by creativefull** [comment] 2015-12-19 06:48
i don't know ,. when i compile my app always got big files ..
do you have solutions for that @luigiplr ?

**Comment by RSATom** [comment] 2015-12-19 06:51
@creativefull, you could try send it directly with email, if you use gmail

**Comment by luigiplr** [comment] 2015-12-19 06:51
@creativefull build it with a installer that has lzma/lzma2 compression: https://github.com/luigiplr/netify-jump/blob/master/util/installer_makensis_x64.nsi

And it will easily bring down a 80MB app down to 40MB.

Also dont package dev deps to further reduce size: https://github.com/luigiplr/netify-jump/blob/master/Gruntfile.js#L79

**Comment by creativefull** [comment] 2015-12-19 06:52
@RSATom What is your email ? rsatom@gmail.com ? it's right ?

**Comment by RSATom** [comment] 2015-12-19 06:53
right

**Comment by creativefull** [comment] 2015-12-19 06:53
@luigiplr OK i'll try ,. Thanks for your info

**Comment by RSATom** [comment] 2015-12-19 06:53
but don't feed spammers...

**Comment by creativefull** [comment] 2015-12-19 06:54
OK

**Comment by luigiplr** [comment] 2015-12-19 06:59
>but don't feed spammers...

_Posts @RSATom's email and username on 4chan._

**Comment by RSATom** [comment] 2015-12-19 07:01
fortunately gmail has pretty good anti-spam :)

**Comment by luigiplr** [comment] 2015-12-19 07:02
hahahha

**Comment by jaruba** [comment] 2015-12-19 07:06
![9d76523fd7990f3112ddb03826514b2b5ad6c82a781e3f774f3ace423d4dd6ef](https://cloud.githubusercontent.com/assets/1777923/11911921/c2c68688-a62f-11e5-89cd-a6fba38d4fe1.jpg)

**Comment by luigiplr** [comment] 2015-12-19 07:10
![](http://gifsec.com/wp-content/uploads/GIF/2014/08/GIF---Creep-Eyebrows-Old-man-Stearing-Stare-Flirt-Flirting--GIF.gif?gs=a)

**Comment by creativefull** [comment] 2015-12-19 07:44
i'm in indonesian , internet very very slow :(
:weary:

**Comment by RSATom** [comment] 2015-12-19 07:54
Ok, then let's try another way. Could you try add path were you installed your app to PATH environment variable? After that run `Dependancy Walker` over `WebChimera.js.node` again.

**Comment by creativefull** [comment] 2015-12-19 07:58
i have been add PATH ,
![path](https://cloud.githubusercontent.com/assets/13174684/11912105/ed9858f6-a660-11e5-8776-932e46bd1faa.PNG)

**Comment by RSATom** [comment] 2015-12-19 08:00
hm... I was talking about your app path, not VLC. But you should **remove** VLC from PATH.

**Comment by RSATom** [comment] 2015-12-19 08:03
if it was ia32 version in your PATH - it could be a reason of your fail.

**Comment by creativefull** [comment] 2015-12-19 08:05
in my PATH using VLC x64 version ..

**Comment by creativefull** [comment] 2015-12-19 08:05
i don't know this bugs, in developer mode it's fine ,.
but when app has been compiled i get like thats

**Comment by creativefull** [comment] 2015-12-19 08:07
@RSATom wait i'll send my app 
![gmail upload](https://cloud.githubusercontent.com/assets/13174684/11912142/2ebffd88-a662-11e5-8b87-a0fe0fb461d8.PNG)

**Comment by RSATom** [comment] 2015-12-19 08:07
just add path where nw.exe from your installation reside to PATH and run `Dependancy Walker`. I want be sure it's not missing some dll or function.

**Comment by RSATom** [comment] 2015-12-19 08:08
ok, waiting

**Comment by creativefull** [comment] 2015-12-19 08:16
yes missing DLL like this.
how to fix it ? :weary: 

![missing dll](https://cloud.githubusercontent.com/assets/13174684/11912172/76133f64-a663-11e5-8c90-346ae7a41977.PNG)

**Comment by RSATom** [comment] 2015-12-19 08:18
most of them should be missing, so it's ok. But don't sure about `bluetoothapis.dll`

**Comment by RSATom** [comment] 2015-12-19 08:20
could you try find what dll require it (in upper-left tree)?

**Comment by creativefull** [comment] 2015-12-19 08:22
i've been send file with you ,. check your email @RSATom

**Comment by creativefull** [comment] 2015-12-19 08:24
test app :)

**Comment by RSATom** [comment] 2015-12-19 08:24
Yes, I've got it...

**Comment by creativefull** [comment] 2015-12-19 08:26
there is an error on your computer ?

**Comment by RSATom** [comment] 2015-12-19 08:26
yes

**Comment by creativefull** [comment] 2015-12-19 08:27
ok , i'll waiting your solution @RSATom :smile:

**Comment by RSATom** [comment] 2015-12-19 08:40
I know the reason - the problem is you rename nw.exe to app.exe. But `WebChimera.js.node` have reference to `nw.exe` inside it.
You have two options:
1) keep `nw.exe` name
2) ask @jaruba, how bind .node module to renamed nw.exe`

**Comment by creativefull** [comment] 2015-12-19 09:01
ok thnks for your solution @RSATom

**Comment by RSATom** [comment] 2015-12-19 09:14
so, can we close this issue?

**Comment by creativefull** [comment] 2015-12-19 09:35
yes, I think you should :D , beside how to bind .node module to renamed nw.exe 
I think it would confused people compiling their apps to other filename.

thanks for the support. you rock  :+1:

**Comment by RSATom** [comment] 2015-12-19 11:37
I think we should create some sort of FAQ...

**Closed by RSATom** 2015-12-19 11:37 UTC

**Comment by jaruba** [comment] 2015-12-19 15:13
@creativefull All the info you need is here: https://github.com/jaruba/wcjs-player/wiki/Suggestions

**Comment by amilajack** [comment] 2016-07-20 06:26
I'm having a similar problem. This is the error I am getting:

```
ELECTRON_ASAR.js:158 Uncaught Error: dlopen(/var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/.popcorn-time-desktop.fIbtSh, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /var/folders/f8/0ty9y5pn3bq0h_yvdxppxnbr0000gn/T/.popcorn-time-desktop.fIbtSh
  Reason: image not found
```

I am using webpack and electron-builder, which compile my code, and I think that they are part of the problem. electron-builder uses a 'two-package.json' structure that requires a package.json (for dev dependencies) in the root folder and another package.json for dependencies that have native bindings. Here's the structure of the app visually:

```
 -- app
    -- package.json
    -- node_modules (production dependencies, contains webchimera.js)
 -- package.json
 -- node_modules (dev dependencies, contains webchimera.js)
```

The compiled output of webpack is located in /app/dist/bundle.js

Feel free to the [packaged app](https://github.com/amilajack/popcorn-time-desktop/releases/download/v0.0.2-alpha/PopcornTime-0.0.3-mac.zip) or you can check out the release-0.0.3-alpha of [the source](https://github.com/amilajack/popcorn-time-desktop) if that makes it easier.

To reproduce, run:
```
// comment lines 78 and 90 of main.development.js to enable devtools in packaged app
npm i
npm run dev // this works fine
// click a tv show in `tv shows` and click `start 720p/1080p` to start
npm run package // this causes the error
// click a tv show in `tv shows` and click `start 720p/1080p` to start, error should occur
```

**Comment by RSATom** [comment] 2016-07-20 06:57
@amilajack, it looks like you are missing `libvlc.5.dylib` or have it in wrong place.

**Comment by amilajack** [comment] 2016-07-20 07:32
This is what is Inside the `/app/node_modules/wcjs-prebuilt/bin/lib` directory:

```
drwxr-xr-x  7 amila  staff     238 Jul 19 23:26 .
drwxr-xr-x  5 amila  staff     170 Jul 19 23:26 ..
-rw-r--r--  1 amila  staff  125408 Jul 19 23:26 libvlc.5.dylib
lrwxr-xr-x  1 amila  staff      14 Jul 19 23:26 libvlc.dylib -> libvlc.5.dylib
-rw-r--r--  1 amila  staff  997072 Jul 19 23:26 libvlccore.8.dylib
lrwxr-xr-x  1 amila  staff      18 Jul 19 23:26 libvlccore.dylib -> libvlccore.8.dylib
drwxr-xr-x  5 amila  staff     170 Jul 19 23:26 vlc
```

**Comment by RSATom** [comment] 2016-07-20 07:37
Unfortunately I don't have access to OS X atm. All I can recommend it - try run `wcjs-ugly-demo`  and if it will work - find out what's wrong with `webpack ` and `electron-builder`

**Comment by amilajack** [comment] 2016-07-20 07:42
Good idea! I will try this tomorrow morning.

**Comment by amilajack** [comment] 2016-07-20 10:05
Fixed it! It was an electron-builder issue with asar. Had to disable it.

**Comment by jaruba** [comment] 2016-07-20 10:12
@amilajack The WebChimera.js binaries (as with all binaries) needs to be outside the asar file in order to work. So you can still use asar, just be sure that all binaries are outside it.
