### ISSUE TITLE
npm pre-builts for NW.js, electron

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#8] opened 2015-05-28 05:47 UTC
Electron can be installed through npm like this: "npm install electron-prebuilt". Which is extremely handy for both development and production points of view.

How about we do that for WebChimera.js?
e.g. `npm install webchimerajs-prebuilt-nw` or `npm install webchimerajs-prebuilt-electron`. Npm can automatically install a platform/arch-specific build. 

What's the most automated way to create builds? Can we make the process entirely automatic?

**Comment by RSATom** [comment] 2015-05-28 05:53
I was thinking about it to, but didn't found any solution yet. The problem is we should support all main platforms (Windows/Mac/Linux) and most engines (NW.js/io.js/Electron). And maybe not only the latest version. I don't know how to solve this task yet.

**Comment by Ivshti** [comment] 2015-05-28 05:54
Also, on Mac and on Windows - VLC has to be embedded in the build. Linux - VLC should be globally installed, but we should also make an option to embed VLC in the build as well.

@RSATom you mean the automatic building? Yes, I have no idea how to do it too.
As for the packaging, two packages for electron/nw are sufficient, since npm can be configured to install different things for different platforms.

**Comment by RSATom** [comment] 2015-05-28 06:01
We don't need two source packages for electron/nw since now engine could be overridden via cmake-js command line. But if we will release binary packages - it will be huge amount of them: 3 platform * 3 engines = 6. And plus ia32 + x64 builds....

**Comment by RSATom** [comment] 2015-05-28 06:02
about embedding VLC - it's another not easy question...

**Comment by Ivshti** [comment] 2015-05-28 06:04
I mean two binary packages. 

To simplify things, we can go with x64 for OS X and Linux (most use cases) and ia32 for Windows ( there are still many 32 bit windows installations ).

Then we have 6 packages. Those would be distributed with 2 npm identifiers (for electron and nw), and npm would decide which package (linux,win,mac) should install for that identifier.

**Comment by RSATom** [comment] 2015-05-28 06:06
yea, but we still need build it somewhere... I will get tired too quickly to build it by hand :)

**Comment by Ivshti** [comment] 2015-05-28 06:07
I'm pretty sure there is a solution for automatic building, we just don't know it yet. The only pre-requisites are a compiler, VLC and node.js.

**Comment by RSATom** [comment] 2015-05-28 06:08
And we still don't know typical use case for `WebChimera.js`. If it will be something like http://isoplex.isohunt.to/ - don't think it will be problem for the to build it from sources...

**Comment by RSATom** [comment] 2015-05-28 06:09
Yes, we need do some investigation. Anyway for first release I will have to do binaries by hand...

**Comment by RSATom** [comment] 2015-05-28 06:21
btw, maybe it worth thinking about create npm package for vlc binaries?

**Comment by sammuel86** [comment] 2015-06-21 17:57
+1 We are using this now in Popcorn time and this would be a welcome addition.

**Comment by RSATom** [comment] 2015-06-24 09:55
Agree, now (when most of API was implemented) it's time to think about binary distribution again.
But I still wonder get some Mac Mini to setup CI server for all platforms...

**Comment by mafintosh** [comment] 2015-07-27 12:03
@RSATom using my prebuild module its easy to do prebuilds for all node versions and upload them to github in a single command. i can help you out setting this up if you're interested

**Comment by RSATom** [comment] 2015-07-27 12:13
@mafintosh, does it provide install script for npm module?

**Comment by Ivshti** [comment] 2015-07-27 13:21
as @mafintosh said in our chat, we can use available services to do that: travis, appveyor.

**Comment by RSATom** [comment] 2015-07-27 16:12
@Ivshti, but we still don't have install script (which will download and extract corresponding archives from some hosting)

**Comment by siuying** [comment] 2015-08-03 11:56
@RSATom [prebuild](https://github.com/mafintosh/prebuild) include support to upload/download binaries, so when user install the package they would download the appropriate package (or the build one if binary is not available). It use node-gyp to build the app, so I dont sure how to integrate with cmake in WebChimera.js. Maybe @mafintosh can help?

**Comment by Ivshti** [comment] 2015-08-23 17:13
Here's a prebuilt module that installs WebChimera.js and VLC bundle for Electron - supports OS X, Linux (x64) and win32 (ia32) 

https://github.com/Ivshti/wcjs-prebuilt

**Comment by siuying** [comment] 2015-08-24 04:37
Thanks @Ivshti , will try it out!!

**Comment by alessiodionisi** [comment] 2015-09-06 17:52
This is my prebuilt for Raspberry Pi 2
https://github.com/alessiodionisi/wcjs-rpi2

**Comment by Ivshti** [comment] 2015-09-06 17:57
that's interesting @alessiodionisi  - can wcjs work fine on the rpi 2?

**Comment by alessiodionisi** [comment] 2015-09-06 18:13
Not quite, I'm working to compile it with hardware acceleration :D
I tried it with a nw.js (https://github.com/jtg-gg/node-webkit/releases) + 1080p video and I got a lot of lags..

**Comment by Ivshti** [comment] 2015-09-06 18:24
TBH, as someone who has developed a launched product built on wcjs and therefore knows the performance bottlenecks, I'd say you can't have it working fine on RPI.

I'd love to be wrong, but the challenges you have to solve are the following:
- Chromium is multi-process - the GPU process which issues commands to the GPU is isolated from the renderer process where wcjs/vlc runs, which means that it always has to copy the texture (video frame) at least once. Even if the GPU process handles texture uploads in the best possible way, you still rely on the CPU to copy the texture
- Chromium is not optimized for the RPI GPU
- VLC relies on software decoding for the most part, while RPI has it's own hardware decoding functionalities. I guess VLC might be adapted to deal with that, but I'm not sure.

I don't want to discourage seeing wcjs on RPI, as I would love that, but those are, unfortunately, large challenges.

Even if you manage to see it working properly - you have to make sure it doesn't take too much resources.

**Comment by Ivshti** [comment] 2015-09-06 19:21
@alessiodionisi here's what I've figured: 

if a linux installed on the RPI allows accelerated framebuffer by copying data into some /dev/... file, we can probably mmap that file and get vlc to draw directly inside it by the vmem back-end which is already used by wc.js

This may or may not work - I have no idea. But if it does work, you won't be able to draw anything on the video

**Comment by RSATom** [comment] 2015-09-23 04:07
fixed with https://github.com/Ivshti/wcjs-prebuilt and Travis-CI/AppVeyor. integration.

**Closed** 2015-09-23 04:07 UTC
Labels: enhancement
