### ISSUE TITLE
Get per frame video frame number

### ISSUE THREAD

**Issue by limoragni** [RSATom/WebChimera.js#92] opened 2016-07-17 12:41 UTC
Is there a way to know the frame number for the frame that's being reproduced? 

I have a file with metadata for each frame of the videos I use and I need to know the exact frame that's being shown in order to render visualizations over the video.

I could infer the frame number using the time or position properties, but those are being refreshed less than 25 times per second. Maybe 3 or 4 times per second I think.

onFrameReady is called once per frame, but it doesn't gives the frame number. 

Do you think there's a way tho achieve this? Is there anything I could do to help with this if there's something that need to be change?

Thanks!
##

**Comment by jaruba** [comment] 2016-07-17 13:58
You pretty much thought of anything I could.. Calculating based on `.time` will definitely have some disadvantages, but less then `onFrameReady` that won't trigger for skipped frames (in case of slow rendering)

Unless @RSATom wants to count the frames inside `WebChimera.js` and pass the frame number to the `onFrameReady` event, I don't see any better way then using something like:
```
Math.round(player.time * 1000 * player.input.fps)
```

What is this for though? Sounds like your trying to make some augmented reality implementation with `WebChimera.js` :))

**Comment by limoragni** [comment] 2016-07-17 16:01
Yeah, that's exactly the line of code I'm using, but is not good enough, it would jump from frame 5 to 10 and so on. What I'm planning on doing is to save the time each time `time` changes and add 1 to that number when `onFrameReady` fires.

We have a football analysis software built using Electron. We show visualizations over the video based on a file with the tracking of the players. So I have a an array with the players position for each frame, and I need to know which frame is being shown so I can know where the player is at that time. I was using HTML5 video but we needed to give support for more video formats so we went with web chimera! The project is great by the way, so far the only problem I have is this one.

**Comment by jaruba** [comment] 2016-07-17 16:41
> What I'm planning on doing is to save the time each time time changes and add 1 to that number when onFrameReady fires.

Well.. you could do that.. or you could just predict the missing frames. With something like:

```
var frame = {
    count: 0,
    interval: false
}

player.onTimeChanged = function(time) {
    frame.interval && clearInterval(frame.interval)
    frame.count = Math.round(time * 1000 * player.input.fps)
    frame.interval = setInterval(function() {
        frame.count++
        console.log('frame number at: ' + frame.count)
    }, Math.round(1000 / player.input.fps))
}

player.onMediaChanged = function() {
    // media has changed, reset frame count
    frame.count = 0
}
```

_untested though_

**Comment by jaruba** [comment] 2016-07-17 16:54
_updated code_

**Comment by jaruba** [comment] 2016-07-17 17:53
I still haven't tested this, I'm quite curios if it works, if it does it should have an accuracy of 1-2 ms. Although `onFrameReady` would be more accurate it would loose some frames completely (due to network issues, performance issues, etc), while predicting should count all frames..

**Comment by RSATom** [comment] 2016-07-18 05:44
@limoragni, unfortunately I don't see any simple and reliable way to get what you need. libvlc just not provide any info related to passed frames. And even if I will count frames inside .node module itself - it will not help, since frames could be dropped inside libvlc.

The possible solutions I see:
1) implement custom libvlc output plugin (something like [vmem2](https://github.com/RSATom/vmem2))
2) switch to use [wcjs-gs](https://github.com/RSATom/wcjs-gs) - it provide pts/dts timestamps for every frame

But bad news is both of above are far from be finished. wcjs-gs now working only on Linux, and have very limited API.

**Comment by limoragni** [comment] 2016-07-18 09:33
I see. Thanks for the input! I wouldn't worry about dropped frames that much if I can correct the synchronisation after a frame was dropped. At the end I'm only interested on showing the visualization only if the frame is drawn . I've implemented a counter that uses the time as a reference every time is available and its working ok. I'm having a problem with the visualizations but I thinks is an unrelated problem. 

Is having the time updated as often as the frames are drawn something that would hurt performance in wcjs? Even though I've solved this with my implementation I think that would make for a good added feature. It would add precision for things like showing a timecode or displaying the time as min:secs:frames (which we also use in our app).

**Comment by RSATom** [comment] 2016-07-18 09:48
> Is having the time updated as often as the frames are drawn something that would hurt performance in wcjs?

The problem is I don't have info about frame timestamp. Libvlc just not give it to me. So to access this info we have to implement custom plugin. It's not so complex task, but just require time to implement it.

**Comment by RSATom** [comment] 2020-12-01 08:01
Closed as too old.

**Closed by RSATom** 2020-12-01 08:01 UTC
Labels: enhancement
