### ISSUE TITLE
Problem in playing DVD the second time [$15]

### ISSUE THREAD

**Issue by heartnetkung** [RSATom/WebChimera.js#43] opened 2015-09-15 11:38 UTC
I tried playing a movie dvd with webchimera.js through mri protocol dvdsimple. The first time it works perfectly. Then when I close the program and run it the second time, it crashes (nw.js window suddenly close after open). The only way to get it working again is to reboot the PC. 

My guess is that there's some native resources that are not released after being used which are associated with the dvd playback. Is there a way I can manually release the resource in JS?

My setup: windowsx64 using nw.js for ia32 and precompiled webchimera.js for ia32

My code below
``` html
<canvas id="canvas" style="width:1080px;height:720px;"></canvas>
<script>
	var wcjs = require("wcjs-renderer");
	var player = wcjs.init(document.getElementById("canvas"));
	player.play("dvdsimple:///D:/");
</script>
```

**Comment by jaruba** [comment] 2015-09-15 13:33
> The first time it works perfectly. Then when I close the program and run it the second time, it crashes (nw.js window suddenly close after open).

- So you open the app, then close it and reopen it?
- Does it work if you just play a normal video file?
- Does it work if you stop playback, clear the playlist then replay the same mrl? (ie: restart playback without restarting the app)
- Did you check the processes after you close the app, are you sure NW.js closes correctly?

**Comment by jaruba** [comment] 2015-09-15 13:52
> My guess is that there's some native resources that are not released after being used which are associated with the dvd playback. Is there a way I can manually release the resource in JS?

From my knowledge, NW.js removes all caches once closed, this includes cookies and any JS resources. While open, it only keeps the required modules in a cache, so every time you use `require()` on the same module, it just grabs it from the cache.

For example, in `wcjs-player`

**Comment by jaruba** [comment] 2015-09-15 14:49
There is one thing you could try though, maybe `WebChimera.js` doesn't have time to deinitialize correctly. In `Powder Player` I delay window close for 1-1.5 seconds (depending on the circumstance), specifically to make sure wcjs has time to finish it's event queue.

    gui = require('nw.gui');
    win = gui.Window.get();
    
    win.on('close', function() {
        win.hide();
        setTimeout(function() {
            win.close(true);
        },1000);
    });

**Comment by heartnetkung** [comment] 2015-09-15 14:59
Thanks for the quick response. Here is some information for your question.

- Does it work if you just play a normal video file?
No
- Does it work if you stop playback, clear the playlist then replay the same mrl? (ie: fully restart playback without restarting the app)
I switch to wcjs-player setup
```
	var wjs = require("wcjs-player");
	window.player = new wjs("#player").addPlayer({
		autoplay: true
	});
	var drive = 'D:/';
	player.addPlaylist("dvdsimple:///" + drive);
// in nwjs console i typed
player.stop()
player.clearPlaylist()
player.addPlaylist("dvdsimple:///D:/")
```
then program immediately crash when I add playlist

- Did you check the processes after you close the app, are you sure NW.js closes correctly?
pretty sure it's closed (all processes left in windows task manager are the same as before opening the app)

- Is your app single-instance or multi-instance? If it's multi-instance, what happens if you just start it two times? Does the second instance break?
single instance

- Are you effectively stopping the playback before closing the app?
yes it's still happen

**Comment by jaruba** [comment] 2015-09-15 15:06
> Does it work if you just play a normal video file? No

This is interesting.. I use `WebChimera.js v0.1.24` in my app and I don't have this issue, I will test `v0.1.30` to see if I can reproduce it.

**Comment by heartnetkung** [comment] 2015-09-15 15:15
@jaruba sorry i misread your question "Does it work if you just play a normal video file?"
yes it works when I play a normal video file

**Comment by jaruba** [comment] 2015-09-15 15:17
seems so, can you try playing that link in VLC, then closing VLC, reopening it and playing it again, does it work? (just to rule out any VLC specific issue too)

**Comment by heartnetkung** [comment] 2015-09-15 15:22
vlc works fine.

**Comment by heartnetkung** [comment] 2015-09-15 15:26
I also tried this code and the problem still occurs
``` html
<div id="player"></div>
	<script>
	var wjs = require("wcjs-player");
	window.player = new wjs("#player").addPlayer({
		autoplay: true
	});
	var gui = require('nw.gui');
	var win = gui.Window.get();

	win.on('close', function() {
		player.stop();
		win.hide();
		setTimeout(function() {
			win.close(true);
		}, 1000);
	});
	var drive = 'D:/';
	player.addPlaylist("dvdsimple:///" + drive);
</script>
```

**Comment by jaruba** [comment] 2015-09-15 15:29
Yeah, it's definitely something in wcjs, I just can't imagine what could be different for a DVD compared to any other MRL, except maybe playlist expansion..

@RSATom should definitely be able to help out more with this from here on.

**Comment by heartnetkung** [comment] 2015-09-15 15:39
@jaruba Thanks for stopping by and help. I really appreciate it. :)

**Comment by RSATom** [comment] 2015-09-15 15:44
@jaruba, did you try open DVD with `wcjs`? If yes, did it work for you?
@heartnetkung, does this problem happens with every dvd, or only some of them?

**Comment by heartnetkung** [comment] 2015-09-15 15:56
@RSATom every DVD. 

Additionally I noticed that sometimes it crashes when the buffer is at 0%, sometimes at 1% (the text on-screen shown by wcjs-player)

**Comment by RSATom** [comment] 2015-09-15 16:00
How does it looks like when it crash? Does it just disappear or show some message?

**Comment by jaruba** [comment] 2015-09-15 16:05
@RSATom I tested a normal file, i believe the circumstance of this bug can be reproduced by mounting any iso of a dvd from torrent sites and trying to play the drive letter as @heartnetkung mentioned above with his example code..

**Comment by RSATom** [comment] 2015-09-15 16:08
@heartnetkung, do you use image of DVD or DVD disk?

**Comment by RSATom** [comment] 2015-09-15 16:09
@heartnetkung, could you please look, do you have files in %LOCALAPPDATA%\CrashDumps ?

**Comment by heartnetkung** [comment] 2015-09-15 16:10
@RSATom when it crashes nothing is showed in neither console or screen. The window just disappear.

I use real DVD

**Comment by heartnetkung** [comment] 2015-09-15 16:13
@RSATom there is no file in the crashdumps even when the -vvv option is used

**Comment by RSATom** [comment] 2015-09-15 16:26
@heartnetkung, could you please create registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps` ( manually or with [this .reg file](https://dl.dropboxusercontent.com/u/94817236/LocalDumps.reg) ), and do crash again?

**Comment by RSATom** [comment] 2015-09-15 16:29
Btw, what Windows and what Vlc version do you use?

**Comment by heartnetkung** [comment] 2015-09-15 16:48
@RSATom 
I use vlc version 2.2.1 windows 7 professional SP1 64bit

**Comment by heartnetkung** [comment] 2015-09-15 16:51
I set the registry as u mentioned (following tutorial from this [link](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx)) but no crash file is generated there.

Rather there are .dmp files generated in %tmp% folder

**Comment by heartnetkung** [comment] 2015-09-15 16:55
These 2 files are generated at the first crash.
http://english-mate.com/2015/crash/2260f529-02a3-4ba5-97db-ed7728a4f1a1.dmp
http://english-mate.com/2015/crash/d1bbe9f2-1a32-4028-9dc9-0e1b8d24d745.dmp

These 2 files are generated at the second crash.
http://english-mate.com/2015/crash/753c2442-ba8d-4ed7-aa46-ff052f44d6b7.dmp
http://english-mate.com/2015/crash/d07048da-14f1-41f1-910d-acb719262dd7.dmp

**Comment by RSATom** [comment] 2015-09-16 05:58
on first look this crash does not related to `WebChimera.js`. What video card do you use? Could you please try update drivers for it?

**Comment by heartnetkung** [comment] 2015-09-16 07:50
AMD Radeon HD 7700

**Comment by heartnetkung** [comment] 2015-09-16 08:13
I updated the driver. The problem still occurs.

**Comment by jaruba** [comment] 2015-09-16 08:24
Are you using any chromium args in your `package.json`? Could you try adding:

    "chromium-args": "--d3d9 --disable-d3d11",

I seriously doubt this is the reason.. but it won't hurt to try, maybe it's a Direct3D 11 compatibility issue...

**Comment by heartnetkung** [comment] 2015-09-16 08:33
More info, I also tried with a new PC with NVDIA GeForce GTX 660 the problem still occurs.

**Comment by heartnetkung** [comment] 2015-09-16 08:42
@jaruba I tried your configuration. Doesn't work so far.

**Comment by RSATom** [comment] 2015-09-16 19:59
> More info, I also tried with a new PC with NVDIA GeForce GTX 660 the problem still occurs.

Hmm... then it's more weird. If you got the same error so easy on other machine - We should get it too, but we don't. Have to understand what's the difference.

**Comment by RSATom** [comment] 2015-09-16 20:01
Does this second PC has clean Windows installed or it being used some time? Maybe there are some software or browser plugins installed on both your computers?

**Comment by heartnetkung** [comment] 2015-09-16 20:47
Both PCs are used for some time now. For browser plugins, both PCs run Chrome with no plugins. Firefox and IE are installed but never used nor installed anything. For other programs, all the video-related stuffs are VLC, Media Player Classic Home Cinema, QuickTime, Skype, Aegisub.

Tomorrow I'll try to repeat the problem in VMware of freshly installed windows and I'll get back to you then.

**Comment by RSATom** [comment] 2015-09-17 06:32
@heartnetkung, you could use prebuilt [virtual machine images](https://dev.modern.ie/tools/vms/windows/) to save some time.

**Comment by heartnetkung** [comment] 2015-09-17 06:42
@RSATom ok thanks

**Comment by heartnetkung** [comment] 2015-09-18 07:07
I got mixed result in VM ware for windows 7 32bit. In our early tries, the first time it works but the video is very laggy and it crashed in the second time as before. Then, we tried daemon tool in hope that the video'd become smooth but now but it doesn't work anymore even the first time. 

Here's the crash dump from the early try:
http://english-mate.com/2015/crash/2fac1726-c15e-452b-a8b1-a8e43f3c76e0.dmp
http://english-mate.com/2015/crash/f9b493e2-27f9-4cfc-a9f4-f1fe6b12da53.dmp

**Comment by heartnetkung** [comment] 2015-09-18 07:16
For reference, here's how I install WebChimera.js. 

Here's the test code

https://github.com/heartnetkung/wcjs-test-DVD

The installation starts from `do_install.bat` that pulls the prebuilt version of wcjs from [this repo](https://github.com/Ivshti/wcjs-prebuilt) and wcjs-player + wcjs-renderer with package.json redirect dependency to the prebuilt version.

**Comment by RSATom** [comment] 2015-09-18 16:22
@heartnetkung, I've got crash with your test code!

**Comment by RSATom** [comment] 2015-09-18 16:43
I think now I know the reason. I hope will fix it tomorrow.

**Closed** 2015-09-19 15:38 UTC
Labels: bounty

**Comment by heartnetkung** [comment] 2015-09-19 20:58
Works like a charm! :)

**Comment by jaruba** [comment] 2015-09-19 21:16
@RSATom 
![gatsby-leo-051113](https://cloud.githubusercontent.com/assets/1777923/9978203/c959647e-5f2c-11e5-8e73-1b8c0a33eaf3.gif)

**Comment by heartnetkung** [comment] 2015-09-19 21:35
@RSATom @jaruba 
![Uploading tumblr_ltt3zzieAQ1r0byljo1_250.gif…]()

**Comment by RSATom** [comment] 2015-09-20 04:50
Great! Thanks!
